/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.dubbo.rpc.protocol.grpc;

import org.apache.dubbo.common.URL;
import org.apache.dubbo.common.logger.Logger;
import org.apache.dubbo.common.logger.LoggerFactory;
import org.apache.dubbo.config.ReferenceConfigBase;
import org.apache.dubbo.rpc.Invoker;
import org.apache.dubbo.rpc.ProtocolServer;
import org.apache.dubbo.rpc.RpcException;
import org.apache.dubbo.rpc.model.FrameworkServiceRepository;
import org.apache.dubbo.rpc.model.ProviderModel;
import org.apache.dubbo.rpc.protocol.AbstractProxyProtocol;

import io.grpc.BindableService;
import io.grpc.CallOptions;
import io.grpc.Channel;
import io.grpc.ManagedChannel;
import io.grpc.Server;
import io.grpc.netty.NettyServerBuilder;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 *
 */
/**
 * GrpcProtocol 类，继承自 AbstractProxyProtocol，用于实现基于 gRPC 的 RPC 协议。
 */
public class GrpcProtocol extends AbstractProxyProtocol {

    // 此处 logger 未使用，可考虑移除
    private static final Logger logger = LoggerFactory.getLogger(GrpcProtocol.class);

    // 默认端口号
    public final static int DEFAULT_PORT = 50051;

    /* <address, gRPC channels> */
    // 存储地址与 gRPC 通道的映射关系
    private final ConcurrentMap<String, ReferenceCountManagedChannel> channelMap = new ConcurrentHashMap<>();
    // 用于同步操作的锁对象
    private final Object lock = new Object();

    /**
     * 导出服务到 gRPC 协议。
     *
     * @param proxiedImpl 代理实现对象
     * @param type        服务接口类型
     * @param url         服务的 URL
     * @param <T>         服务接口类型的泛型
     * @return 一个 Runnable 对象，用于移除服务
     * @throws RpcException 当导出服务过程中发生错误时抛出
     */
    @Override
    protected <T> Runnable doExport(T proxiedImpl, Class<T> type, URL url) throws RpcException {
        // 获取服务地址
        String key = url.getAddress();
        // 如果服务地址对应的服务器不存在，则创建一个新的服务器
        ProtocolServer protocolServer = serverMap.computeIfAbsent(key, k -> {
            // 创建一个 Dubbo 处理器注册表
            DubboHandlerRegistry registry = new DubboHandlerRegistry();

            // 构建 Netty 服务器
            NettyServerBuilder builder =
                    NettyServerBuilder
                    .forPort(url.getPort())
                            .fallbackHandlerRegistry(registry);

            // 构建原始的 gRPC 服务器
            Server originalServer = GrpcOptionsUtils.buildServerBuilder(url, builder).build();
            // 创建一个 gRPC 远程服务器
            GrpcRemotingServer remotingServer = new GrpcRemotingServer(originalServer, registry);
            // 返回一个代理协议服务器
            return new ProxyProtocolServer(remotingServer);
        });

        // 获取 gRPC 远程服务器
        GrpcRemotingServer grpcServer = (GrpcRemotingServer) protocolServer.getRemotingServer();

        // 获取框架服务仓库
        FrameworkServiceRepository serviceRepository = frameworkModel.getServiceRepository();
        // 查找导出的服务模型
        ProviderModel providerModel = serviceRepository.lookupExportedService(url.getServiceKey());
        if (providerModel == null) {
            // 如果服务模型不存在，抛出异常
            throw new IllegalStateException("Service " + url.getServiceKey() + "should have already been stored in service repository, " +
                    "but failed to find it.");
        }
        // 获取原始的服务实例
        Object originalImpl = providerModel.getServiceInstance();

        // 获取服务实现类
        Class<?> implClass = originalImpl.getClass();
        try {
            // 获取设置代理实现的方法
            Method method = implClass.getMethod("setProxiedImpl", type);
            // 调用方法设置代理实现
            method.invoke(originalImpl, proxiedImpl);
        } catch (Exception e) {
            // 如果设置代理实现失败，抛出异常
            throw new IllegalStateException("Failed to set dubbo proxied service impl to stub, please make sure your stub " +
                    "was generated by the dubbo-protoc-compiler.", e);
        }
        // 将服务添加到注册表中
        grpcServer.getRegistry().addService((BindableService) originalImpl, url.getServiceKey());

        // 如果服务器未启动，则启动服务器
        if (!grpcServer.isStarted()) {
            grpcServer.start();
        }

        // 返回一个 Runnable 对象，用于移除服务
        return () -> grpcServer.getRegistry().removeService(url.getServiceKey());
    }

    /**
     * 引用 gRPC 协议的服务。
     *
     * @param type 服务接口类型
     * @param url  服务的 URL
     * @param <T>  服务接口类型的泛型
     * @return 一个 Invoker 对象，用于调用服务
     * @throws RpcException 当引用服务过程中发生错误时抛出
     */
    @Override
    protected <T> Invoker<T> protocolBindingRefer(final Class<T> type, final URL url) throws RpcException {
        // 获取服务接口的外部类
        Class<?> enclosingClass = type.getEnclosingClass();

        if (enclosingClass == null) {
            // 如果外部类不存在，抛出异常
            throw new IllegalArgumentException(type.getName() + " must be declared inside protobuf generated classes, " +
                    "should be something like ServiceNameGrpc.IServiceName.");
        }

        // 获取创建 Dubbo 存根的方法
        final Method dubboStubMethod;
        try {
            dubboStubMethod = enclosingClass.getDeclaredMethod("getDubboStub", Channel.class, CallOptions.class,
                    URL.class, ReferenceConfigBase.class);
        } catch (NoSuchMethodException e) {
            // 如果方法不存在，抛出异常
            throw new IllegalArgumentException("Does not find getDubboStub in " + enclosingClass.getName() + ", please use the customized protoc-gen-dubbo-java to update the generated classes.");
        }

        // 获取共享的 gRPC 通道
        ReferenceCountManagedChannel channel = getSharedChannel(url);

        // 创建 Dubbo 存根
        try {
            // 获取服务引用配置
            ReferenceConfigBase<?> referenceConfig = url.getServiceModel().getReferenceConfig();
            @SuppressWarnings("unchecked") final T stub = (T) dubboStubMethod.invoke(null,
                    channel,
                    GrpcOptionsUtils.buildCallOptions(url),
                    url,
                    referenceConfig
            );
            // 创建 Invoker 对象
            final Invoker<T> target = proxyFactory.getInvoker(stub, type, url);
            // 创建 gRPC Invoker 对象
            GrpcInvoker<T> grpcInvoker = new GrpcInvoker<>(type, url, target, channel);
            // 将 Invoker 对象添加到列表中
            invokers.add(grpcInvoker);
            return grpcInvoker;
        } catch (IllegalAccessException | InvocationTargetException e) {
            // 如果创建存根失败，抛出异常
            throw new IllegalStateException("Could not create stub through reflection.", e);
        }
    }

    /**
     * 该方法未使用，不支持调用。
     *
     * @param type 服务接口类型
     * @param url  服务的 URL
     * @param <T>  服务接口类型的泛型
     * @return 不支持调用，抛出 UnsupportedOperationException
     * @throws RpcException 不支持调用，抛出 UnsupportedOperationException
     */
    @Override
    protected <T> T doRefer(Class<T> type, URL url) throws RpcException {
        throw new UnsupportedOperationException("not used");
    }

    /**
     * 获取共享的 gRPC 通道连接。
     *
     * @param url 服务的 URL
     * @return 共享的 gRPC 通道
     */
    private ReferenceCountManagedChannel getSharedChannel(URL url) {
        // 获取服务地址
        String key = url.getAddress();
        // 从通道映射中获取通道
        ReferenceCountManagedChannel channel = channelMap.get(key);

        if (channel != null && !channel.isTerminated()) {
            // 如果通道存在且未终止，增加引用计数
            channel.incrementAndGetCount();
            return channel;
        }

        // 同步块，确保线程安全
        synchronized (lock) {
            channel = channelMap.get(key);
            // 再次检查通道是否存在且未终止
            if (channel != null && !channel.isTerminated()) {
                // 如果通道存在且未终止，增加引用计数
                channel.incrementAndGetCount();
            } else {
                // 如果通道不存在或已终止，创建一个新的通道
                channel = new ReferenceCountManagedChannel(initChannel(url));
                // 将新通道添加到通道映射中
                channelMap.put(key, channel);
            }
        }

        return channel;
    }

    /**
     * 创建一个新的 gRPC 通道连接。
     *
     * @param url 服务的 URL
     * @return 新的 gRPC 通道
     */
    private ManagedChannel initChannel(URL url) {
        // 使用 GrpcOptionsUtils 构建一个新的通道
        return GrpcOptionsUtils.buildManagedChannel(url);
    }

    /**
     * 获取默认端口号。
     *
     * @return 默认端口号
     */
    @Override
    public int getDefaultPort() {
        return DEFAULT_PORT;
    }

    /**
     * 销毁协议，关闭所有服务器和通道。
     */
    @Override
    public void destroy() {
        // 关闭所有服务器
        serverMap.values().forEach(ProtocolServer::close);
        // 关闭所有通道
        channelMap.values().forEach(ReferenceCountManagedChannel::shutdown);
        // 清空服务器映射
        serverMap.clear();
        // 清空通道映射
        channelMap.clear();
        // 调用父类的销毁方法
        super.destroy();
    }

    /**
     * GrpcRemotingServer 类，继承自 RemotingServerAdapter，用于管理 gRPC 服务器。
     */
    public class GrpcRemotingServer extends RemotingServerAdapter {

        // 原始的 gRPC 服务器，建议声明为 final
        private Server originalServer;
        // Dubbo 处理器注册表，建议声明为 final
        private DubboHandlerRegistry handlerRegistry;
        // 服务器是否已启动的标志
        private volatile boolean started;

        /**
         * 构造函数，初始化 gRPC 远程服务器。
         *
         * @param server          原始的 gRPC 服务器
         * @param handlerRegistry Dubbo 处理器注册表
         */
        public GrpcRemotingServer(Server server, DubboHandlerRegistry handlerRegistry) {
            this.originalServer = server;
            this.handlerRegistry = handlerRegistry;
        }

        /**
         * 启动 gRPC 服务器。
         *
         * @throws RpcException 当启动服务器过程中发生错误时抛出
         */
        public void start() throws RpcException {
            try {
                // 启动原始的 gRPC 服务器
                originalServer.start();
                // 设置服务器已启动标志
                started = true;
            } catch (IOException e) {
                // 如果启动失败，抛出异常
                throw new RpcException("Starting gRPC server failed. ", e);
            }
        }

        /**
         * 获取 Dubbo 处理器注册表。
         *
         * @return Dubbo 处理器注册表
         */
        public DubboHandlerRegistry getRegistry() {
            return handlerRegistry;
        }

        /**
         * 获取代理服务器对象。
         *
         * @return 代理服务器对象
         */
        @Override
        public Object getDelegateServer() {
            return originalServer;
        }

        /**
         * 检查服务器是否已启动。
         *
         * @return 如果服务器已启动，返回 true；否则返回 false
         */
        public boolean isStarted() {
            return started;
        }

        /**
         * 关闭 gRPC 服务器。
         */
        @Override
        public void close() {
            // 关闭原始的 gRPC 服务器
            originalServer.shutdown();
        }
    }

}
